# Generated by Django 5.0.6 on 2024-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('auditor', 'Auditor'), ('supervisor', 'Supervisor'), ('jefe_auditoria', 'Jefe de Auditoría')], default='auditor', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='auditorias_asignadas',
            field=models.ManyToManyField(related_name='auditorias_asignadas', to='users.auditoria'),
        ),
    ]
