# Generated by Django 5.0.6 on 2024-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditoria_user_role_user_auditorias_asignadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('auditor', 'Auditor'), ('supervisor', 'Supervisor'), ('jefe_auditoria', 'Jefe de Auditoría')], default=('auditor', 'Auditor'), max_length=20),
        ),
    ]
