# Generated by Django 5.0.6 on 2024-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('auditor', 'Auditor'), ('supervisor', 'Supervisor'), ('jefe_auditoria', 'Jefe de Auditoría')], default='auditor', max_length=20),
        ),
    ]
