# Generated by Django 5.0.6 on 2024-06-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auditorias_asignadas',
            field=models.ManyToManyField(blank=True, related_name='auditorias_asignadas', to='users.auditoria'),
        ),
    ]
