# Generated by Django 5.0.6 on 2024-06-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_auditorias_asignadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auditorias_asignadas',
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
