# Generated by Django 5.0.6 on 2024-06-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_auditorias_asignadas_delete_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
