# Generated by Django 5.0.6 on 2024-06-26 23:53

from django.db import migrations
import uuid


def generate_uuids(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.signature = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_signature"),
    ]

    operations = [
        migrations.RunPython(generate_uuids),
    ]
