# Generated by Django 5.0.6 on 2024-06-26 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fill_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
