# Generated by Django 5.0.6 on 2024-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
        ('users', '0009_alter_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auditorias_asignadas',
            field=models.ManyToManyField(blank=True, related_name='auditorias_asignadas', to='auditorias.auditoria'),
        ),
    ]
