# Generated by Django 5.0.6 on 2024-06-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstatus',
            name='readed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
